import type { Attendee, Coordinates, Game } from "./types";

export const FALLBACK_CENTER: Coordinates = {
    latitude: -22.9056,
    longitude: -47.0608,
};

function inHours(hours: number): string {
    return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
}

function people(names: string[], arrivedCount: number): Attendee[] {
    return names.map((name, index) => ({
        playerId: `seed-${name.toLowerCase()}-${index}`,
        name,
        arrived: index < arrivedCount,
    }));
}

export function seedGames(): Game[] {
    return [
        {
            id: "gm-01",
            ownerId: "seed",
            source: "local",
            sport: "Basquete",
            modality: "3x3",
            placeName: "Quadra do Taquaral",
            startsAt: inHours(-0.5),
            durationMinutes: 90,
            level: "intermediario",
            spots: 6,
            status: "em-andamento",
            coordinates: { latitude: -22.8912, longitude: -47.0521 },
            attendees: people(
                ["Bruno", "Carla", "Diego", "Elis", "Fábio", "Gabi"],
                6,
            ),
            score: { home: 11, away: 8 },
        },
        {
            id: "gm-02",
            ownerId: "seed",
            source: "local",
            sport: "Futsal",
            modality: "5x5",
            placeName: "Ginásio do Cambuí",
            startsAt: inHours(2),
            durationMinutes: 90,
            level: "iniciante",
            spots: 10,
            status: "aberto",
            coordinates: { latitude: -22.8983, longitude: -47.0492 },
            attendees: people(
                ["Ana", "Caio", "Duda", "Rafa", "Tiago", "Vini", "Léo"],
                3,
            ),
            score: { home: 0, away: 0 },
        },
        {
            id: "gm-03",
            ownerId: "seed",
            source: "local",
            sport: "Vôlei",
            modality: "4x4",
            placeName: "Areia do Parque Portugal",
            startsAt: inHours(3),
            durationMinutes: 90,
            level: "intermediario",
            spots: 8,
            status: "aberto",
            coordinates: { latitude: -22.8864, longitude: -47.0577 },
            attendees: people(["Bia", "Gabi", "Nina", "Paula", "Rita"], 1),
            score: { home: 0, away: 0 },
        },
        {
            id: "gm-04",
            ownerId: "seed",
            source: "local",
            sport: "Basquete",
            modality: "5x5",
            placeName: "Praça Arautos da Paz",
            startsAt: inHours(5),
            durationMinutes: 90,
            level: "avancado",
            spots: 10,
            status: "aberto",
            coordinates: { latitude: -22.9187, longitude: -47.0663 },
            attendees: people(
                [
                    "Igor",
                    "Juca",
                    "Kau",
                    "Marcos",
                    "Nando",
                    "Otto",
                    "Pedro",
                    "Rui",
                    "Sam",
                    "Théo",
                ],
                0,
            ),
            score: { home: 0, away: 0 },
        },
        {
            id: "gm-05",
            ownerId: "seed",
            source: "local",
            sport: "Futebol",
            modality: "Society 7x7",
            placeName: "Society Barão Geraldo",
            startsAt: inHours(6),
            durationMinutes: 90,
            level: "intermediario",
            spots: 14,
            status: "aberto",
            coordinates: { latitude: -22.8321, longitude: -47.0699 },
            attendees: people(["Alan", "Bento", "Cris", "Davi"], 0),
            score: { home: 0, away: 0 },
        },
        {
            id: "gm-06",
            ownerId: "seed",
            source: "local",
            sport: "Futsal",
            modality: "5x5",
            placeName: "Quadra do Jardim Aurélia",
            startsAt: inHours(9),
            durationMinutes: 90,
            level: "iniciante",
            spots: 10,
            status: "aberto",
            coordinates: { latitude: -22.9421, longitude: -47.0812 },
            attendees: people(["Edu", "Fer", "Gui"], 0),
            score: { home: 0, away: 0 },
        },
        {
            id: "gm-07",
            ownerId: "seed",
            source: "local",
            sport: "Basquete",
            modality: "3x3",
            placeName: "Quadra da Vila Industrial",
            startsAt: inHours(12),
            durationMinutes: 90,
            level: "iniciante",
            spots: 6,
            status: "aberto",
            coordinates: { latitude: -22.9265, longitude: -47.0521 },
            attendees: people(["Hugo", "Iva"], 0),
            score: { home: 0, away: 0 },
        },
        {
            id: "gm-08",
            ownerId: "seed",
            source: "local",
            sport: "Vôlei",
            modality: "6x6",
            placeName: "Ginásio da Unicamp",
            startsAt: inHours(20),
            durationMinutes: 90,
            level: "avancado",
            spots: 12,
            status: "aberto",
            coordinates: { latitude: -22.8184, longitude: -47.0647 },
            attendees: people(["Lia", "Malu", "Sofia", "Val", "Yara"], 0),
            score: { home: 0, away: 0 },
        },
    ];
}
